### ISSUE TITLE
Multi-line textfield in demo squashed on OSX

### ISSUE THREAD

**Issue by ianharrigan** [haxeui/hxWidgets#27]
![image](https://cloud.githubusercontent.com/assets/3024242/15105971/4092e98e-15c6-11e6-9082-4f2cc8eb5623.png)

**Comment by sumo961** [comment]
In the latest build, some of the vertical controls look strange on a mac

![vertical](https://cloud.githubusercontent.com/assets/11142464/17134242/c76a6a54-5329-11e6-95e4-871e52f121d9.png)

**Comment by ianharrigan** [comment]
hmmmm... thats strange... are they supposed to be vertical progressbars? And that is just the demo app? No changes?

**Comment by sumo961** [comment]
No - just compiled with the latest HXCPP release version and no changes.
Everything else is like before.

**Comment by sumo961** [comment]
Still looks the same with current build
