### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by sumo961** [haxeui/hxWidgets#38]
latest version does not compile for me:

Compiling group 'haxe' with flags -Iinclude -I/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.0/lib/wx/include/osx_cocoa-unicode-3.0 -I/opt/local/Library/Frameworks/wxWidgets.framework/Versions/wxWidgets/3.0/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -fvisibility=hidden -O2 -I/usr/local/lib/haxe/lib/hxcpp/3,3,49/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=321(haxe) tags=[haxe,static]
.....
./src/hx/widgets/Size.cpp:87:1: error: no viable conversion from 'const Dynamic' to 'wxSize'
STATIC_HX_DEFINE_DYNAMIC_FUNC1(Size_obj,copy,return )

**Comment by ibilon** [comment]
This commit https://github.com/haxeui/hxWidgets/commit/641050313854960481ca3e023bd517dc6da912e6 should have fixed this.

Could you retest and close if it works?
