### ISSUE TITLE
nmake from different directory - windows

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/hxWidgets#42]
Instructions said to 
`nmake.exe -f %WXWIN%\build\msw\makefile.vc BUILD=release`

So I started a command from directoru %WXWIN%, but I found that i had to cd to %WXWIN%\build\msw\ and use
`nmake.exe -f makefile.vc BUILD=release`

I dont know if it will help anyone but...there it is

**Comment by datee** [comment]
Thanks! I had the same error. Perhaps the instructions should be updated?

**Comment by ianharrigan** [comment]
OK, so someone else had to do this too, so will update the instructions.

**Comment by ianharrigan** [comment]
Add a note to the readme file. Can you close this if it makes sense? 

Cheers.
