### ISSUE TITLE
Basic test not working

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/hxWidgets#43]
I am using 
Haxe:3.4.0
hxcpp: 3.4.22
HaxeUI-hxWidgets: git

When running the included app I get
`Called from hxcpp::__hxcpp_main
Called from Main::main Main.hx line 13
Called from haxe.ui.HaxeUIApp::ready haxe/ui/HaxeUIApp.hx line 15
Called from haxe.ui.HaxeUIApp::init haxe/ui/HaxeUIApp.hx line 24
Called from haxe.ui.backend.AppBase::init haxe/ui/backend/AppBase.hx line 70
Called from Main::main Main.hx line 150
Called from haxe.ui.components.Label::new haxe/ui/components/Label.hx line 19
Called from haxe.ui.core.InteractiveComponent::new haxe/ui/core/InteractiveComponent.hx line 10
Called from haxe.ui.core.Component::new haxe/ui/core/Component.hx line 58
Called from haxe.ui.core.Component::addClass haxe/ui/core/Component.hx line 704
Called from haxe.ui.core.Component::invalidateStyle haxe/ui/core/Component.hx line 1640
Called from haxe.ui.components.Label::applyStyle haxe/ui/components/Label.hx line 56
Called from haxe.ui.core.Component::applyStyle haxe/ui/core/Component.hx line 1664
Called from haxe.ui.core.Component::set_native haxe/ui/core/Component.hx line 215
Called from haxe.ui.components.Label::create haxe/ui/components/Label.hx line 36
Called from haxe.ui.core.Component::create haxe/ui/core/Component.hx line 81
Called from haxe.ui.core.Component::createLayout haxe/ui/core/Component.hx line 111
Error : Null Object Reference`

[TreeTest.zip](https://github.com/haxeui/hxWidgets/files/667264/TreeTest.zip)

**Comment by ianharrigan** [comment]
Can you run the test app in hxWidgets? Ie, remove haxeui from the equation.

**Comment by ianharrigan** [comment]
Also, haxe 3.4... no idea... @ibilon - you tend to be "cutting edge" does hxWidgets (no haxeui) work with haxe 3.4 (if you have it installed - which you probably do)

**Comment by hoseyjoe** [comment]
test app in hxWidgets worked in haxedevelop "debug" but not "release".  But that is probably not related to haxeui-hxWidgets

**Comment by hoseyjoe** [comment]
So it only appears tobe broken for me.  Wondw why? In my builds/hxwidgets folder I get an Options.txt file with
`ABI=-MD
WXSTATIC=1
haxe3=1
haxe_ver=3.4
haxeui-core=0.0.0
haxeui-hxwidgets=0.0.0
haxeui_core=0.0.0
haxeui_hxwidgets=0.0.0
hscript=1
hxWidgets=0.0.1
hxcpp=3.4.31
hxcpp_api_level=331
source-header=GeneratedByHaxe
source_header=GeneratedByHaxe
hxcpp=C:\sdks\haxe3\haxe\lib\hxcpp/3,4,31/`

**Comment by hoseyjoe** [comment]
Duplicate issue with Haxe 3.4 rc1
https://github.com/haxeui/haxeui-hxwidgets/issues/4
