### ISSUE TITLE
Compilation failure(s)

### ISSUE THREAD

**Issue by jacekszymanski** [haxeui/hxWidgets#44]
On OSX El Capitan, while trying to compile 00-Showcase:

```
Error: While running :g++ -I/Users/jsz/dev/tmp2/hxWidgets/samples/00-Showcase/bin/obj/darwin64/__pch/haxe -Iinclude -I/opt/brew/lib/wx/include/osx_cocoa-unicode-3.0 -I/opt/brew/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -fvisibility=hidden -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -O2 -I/usr/local/lib/haxe/lib/hxcpp/git/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=331 -x c++ -frtti -Wno-invalid-offsetof ./src/hx/widgets/ComboBox.cpp -o/Users/jsz/dev/tmp2/hxWidgets/samples/00-Showcase/bin/obj/darwin64/edf3cd3c_ComboBox.o
./src/hx/widgets/ComboBox.cpp:81:26: error: no matching member function for call to 'Create'
HXDLIN(  13)                            _hx_tmp->Create(_hx_tmp1,id,_hx_tmp2,_hx_tmp3,_hx_tmp4,(int)0,(int)0,style);
                                        ~~~~~~~~~^~~~~~
/opt/brew/include/wx-3.0/wx/osx/combobox.h:77:10: note: candidate function not viable: no known conversion from 'int' to 'const wxString *' for 7th argument
    bool Create(wxWindow *parent, wxWindowID id,
         ^
/opt/brew/include/wx-3.0/wx/osx/combobox.h:86:10: note: candidate function not viable: no known conversion from 'int' to 'const wxArrayString' for 6th argument
    bool Create(wxWindow *parent, wxWindowID id,
         ^
./src/hx/widgets/ComboBox.cpp:91:27: error: no matching member function for call to 'Create'
HXDLIN(  17)                            _hx_tmp5->Create(_hx_tmp6,id,_hx_tmp7,_hx_tmp8,_hx_tmp9,(int)0,(int)0,style);
                                        ~~~~~~~~~~^~~~~~
/opt/brew/include/wx-3.0/wx/osx/combobox.h:77:10: note: candidate function not viable: no known conversion from 'int' to 'const wxString *' for 7th argument
    bool Create(wxWindow *parent, wxWindowID id,
         ^
/opt/brew/include/wx-3.0/wx/osx/combobox.h:86:10: note: candidate function not viable: no known conversion from 'int' to 'const wxArrayString' for 6th argument
    bool Create(wxWindow *parent, wxWindowID id,
         ^
2 errors generated.
/Users/jsz/dev/tmp2/hxWidgets/src/wx/widgets/WxString.hx:11: characters 11-17 : Warning : Unrecognized analyzer option: as_var
Error: Build failed
```

and Buttons from haxeui-examples:
```
Error: While running :g++ -I/Users/jsz/dev/tmp2/haxeui-examples/Buttons/build/hxwidgets/obj/darwin64/__pch/haxe -Iinclude -I/opt/brew/lib/wx/include/osx_cocoa-unicode-3.0 -I/opt/brew/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__  -mmacosx-version-min=10.7 -std=c++11 -stdlib=libc++ -c -fvisibility=hidden -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -O2 -I/usr/local/lib/haxe/lib/hxcpp/git/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=331 -x c++ -frtti -Wno-invalid-offsetof ./src/hx/widgets/ClassInfo.cpp -o/Users/jsz/dev/tmp2/haxeui-examples/Buttons/build/hxwidgets/obj/darwin64/edf3cd3c_ClassInfo.o
./src/hx/widgets/ClassInfo.cpp:44:71: error: member reference base type 'const wxChar *' (aka 'const wchar_t *') is not a structure or union
HXLINE(  20)            return ::String(::String(this->_ref->ptr->GetClassName().c_str().AsChar()));
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
1 error generated.
/Users/jsz/dev/tmp2/hxWidgets/src/wx/widgets/WxString.hx:11: characters 11-17 : Warning : Unrecognized analyzer option: as_var
Error: Build failed
```

**Comment by ianharrigan** [comment]
Do you know what version of wxWidgets you are using?

**Comment by jacekszymanski** [comment]
Yes, freshly installed from brew `wxmac-3.0.2_4.el_capitan.bottle.tar.gz`. Also, all haxelibs updated from git just before.

**Comment by calangoni** [comment]
I have the same problem on linux

**Comment by ianharrigan** [comment]
Which versions of hxcpp / haxe?

**Comment by calangoni** [comment]
Haxe 3.4.0 and hxcpp from git (up to date)

**Comment by jacekszymanski** [comment]
Changing ```cast 0``` to ```null``` in these lines (13, 17; and a similar change in ```Choice.hx```) allows the sample to compile, but I don't know how it would affect other platforms than mac.

**Comment by ianharrigan** [comment]
Great news! That works just fine this end @ibilon - any chance you could give it a run through on linux?

**Comment by ibilon** [comment]
Will do.

@jacekszymanski does changing `cast 0` to `untyped __cpp__("NULL")` works too?

**Comment by calangoni** [comment]
I did the 3 modifications proposed by @jacekszymanski and it worked for me on Arch Linux. I could compile and run the sample. Thanks!

**Comment by ianharrigan** [comment]
OK, can you try latest and if it works, can we close this? Should be fixed now (hopefully)...

**Comment by jacekszymanski** [comment]
@ibilon  Yes it works, both examples compile.

**Comment by ianharrigan** [comment]
OK, this is great, i think the null is probably the more correct choice, this fix should be in github now, so can you close this if that version works.

Cheers,
Ian

PS: any chance we could see some screens?

**Comment by jacekszymanski** [comment]
Yes it works.

Screens of? Showcase on mac?

**Comment by ianharrigan** [comment]
Yeah, would be interesting

**Comment by jacekszymanski** [comment]
Sure, will make some, probably on the weekend.

**Comment by jacekszymanski** [comment]
Here you are:

![hx01](https://cloud.githubusercontent.com/assets/208228/23834042/d1e00662-074f-11e7-92b7-2cfaf451af50.png)
![hx02](https://cloud.githubusercontent.com/assets/208228/23834043/d1e0fbd0-074f-11e7-8062-7ca757202589.png)
![hx03](https://cloud.githubusercontent.com/assets/208228/23834044/d1e1d212-074f-11e7-8bcf-c1451858e8f8.png)
![hx04](https://cloud.githubusercontent.com/assets/208228/23834045/d1e20f7a-074f-11e7-9355-7ab78847c3b2.png)
![hx05](https://cloud.githubusercontent.com/assets/208228/23834047/d1e42314-074f-11e7-9827-198e4140e994.png)
![hx06](https://cloud.githubusercontent.com/assets/208228/23834046/d1e3d012-074f-11e7-897d-b54aef099f9f.png)
![hx07](https://cloud.githubusercontent.com/assets/208228/23834048/d1fbb402-074f-11e7-952b-e28e50918e05.png)
![hx08](https://cloud.githubusercontent.com/assets/208228/23834049/d1fda064-074f-11e7-845a-27d5512fc603.png)
![hx09](https://cloud.githubusercontent.com/assets/208228/23834050/d203b03a-074f-11e7-8f69-a6af78f6d300.png)
![hx10](https://cloud.githubusercontent.com/assets/208228/23834051/d203d45c-074f-11e7-8904-ecf086607c4b.png)
![hx11](https://cloud.githubusercontent.com/assets/208228/23834052/d203e4e2-074f-11e7-97fc-834b522c0c07.png)

**Comment by ianharrigan** [comment]
Fantastic, thanks! Looks ok for the most part... vertical components dont look right, neither does multiline text box... but apart from that looks ok. 

Thanks again!
Ian
