### ISSUE TITLE
Components loose modern theme - Manifest issue?

### ISSUE THREAD

**Issue by datee** [haxeui/hxWidgets#50]
[Windows] Building static and running the application from the build dir works fine, but if i copy it to a different location i loose the components theme, and it all looks like "windows 95" style. 

Seems to be related to manifest not being properly set up or something?

**Comment by ianharrigan** [comment]
... Oh - thats a fun one - same happens to me!

**Comment by ianharrigan** [comment]
![image](https://user-images.githubusercontent.com/3024242/31765990-97cc85a2-b4c6-11e7-9de5-b4c0d6a621ba.png)

So i can fix it by manually adding a manifest resource to the app. :(

Wonder why it works from the build dir though

**Comment by ianharrigan** [comment]
Can you update hxWidgets try this again? Should be fixed now as the manifest get linked into the exe by the compiler.

**Comment by datee** [comment]
Wow, that was fast :) 
Ok, tried it.. but seem to get a linker error:
LINK : fatal error LNK1158: cannot run 'mt.exe'

**Comment by ianharrigan** [comment]
... which you didnt get before?

**Comment by datee** [comment]
yes, this linker error came now because of the new fix

**Comment by ianharrigan** [comment]
Hmm, so if you remove the new lines it compiles? What version of MSVC?

**Comment by ianharrigan** [comment]
This any help? https://stackoverflow.com/questions/30725256/fatal-error-lnk1158-cannot-run-mt-exe

**Comment by datee** [comment]
Yes i had the RC.exe error in the link too, but i fixed that.
Oddly enough, i removed the line, recompiled and added it again; suddenly everything compiled ok.

**Comment by ianharrigan** [comment]
Strange, does it also fix the original issue?

**Comment by datee** [comment]
But; commenting out this line fixes the issue:

**Comment by ianharrigan** [comment]
really? That doesnt seem to make much sense... Does it have a manifest file inside the .exe (Using ResourceHacker for example)

**Comment by ianharrigan** [comment]
ok, `/MANIFEST:EMBED` embed a default manifest... cool - will update

**Comment by ianharrigan** [comment]
Right, should be fixed now in master - can you close this once you are happy and its working - thanks!

**Comment by datee** [comment]
Cool! It seems to work, will test a bit on some others computers first!

**Comment by datee** [comment]
Fixed!
