### ISSUE TITLE
failed compilation with MinGW

### ISSUE THREAD

**Issue by r3d9u11** [haxeui/hxWidgets#51]
Hi. I tried to compile a simple application on Windows with MinGW. Also I have already installed  wxWidgets library (by default path C:\wxWidgets-3.1.0).

my build.hxml:
```
-main Main
-cp Source
-cpp Bin

-lib hscript
-lib hxWidgets
-lib haxeui-core
-lib haxeui-hxwidgets

-D ABI=-MD
-D WXSTATIC

-D HXCPP_MINGW
-D MINGW_ROOT=C:\Program Files (x86)\mingw-w64\i686-7.2.0-posix-dwarf-rt_v5-rev1\mingw32
```

exception:
```
...
 - src/wx/widgets/styles/WindowStyle.cpp
Error: In file included from ./src/wx/widgets/styles/WindowStyle.cpp:5:0:
include/wx/widgets/styles/WindowStyle.h:11:10: fatal error: wx/window.h: No such file or directory
 #include <wx/window.h>
          ^~~~~~~~~~~~~
compilation terminated.
Error: Build failed
```
I think that I must manually to define path to wxWidgets *.h files, right? But how to do it most correctly?
Thanks.

**Comment by ianharrigan** [comment]
On the main README there should be instructions, this one in particular: 

* Create WXWIN environment var if setup didnt (eg: C:\wxWidgets-3.0.2)

If i remember rightly i didnt end up with that env var and had to manually create it. Let me know if the any of those instructions need updating too

Cheers

**Comment by r3d9u11** [comment]
something wrong with path separator:

WINWX = C:\wxWidgets-3.1.0
```
Error: In file included from C:\wxWidgets-3.1.0\include/wx/defs.h:20:0,
                 from C:\wxWidgets-3.1.0\include/wx/event.h:14,
                 from C:\wxWidgets-3.1.0\include/wx/window.h:18,
                 from include/wx/widgets/styles/WindowStyle.h:11,
                 from ./src/wx/widgets/styles/WindowStyle.cpp:5:
C:\wxWidgets-3.1.0\include/wx/platform.h:136:10: fatal error: wx/setup.h: No such file or directory
 #include "wx/setup.h"
          ^~~~~~~~~~~~
compilation terminated.
Error: Build failed
```
WINWX = C:/wxWidgets-3.1.0
```
Error: In file included from C:/wxWidgets-3.1.0\include/wx/defs.h:20:0,
                 from C:/wxWidgets-3.1.0\include/wx/event.h:14,
                 from C:/wxWidgets-3.1.0\include/wx/window.h:18,
                 from include/wx/widgets/styles/WindowStyle.h:11,
                 from ./src/wx/widgets/styles/WindowStyle.cpp:5:
C:/wxWidgets-3.1.0\include/wx/platform.h:136:10: fatal error: wx/setup.h: No such file or directory
 #include "wx/setup.h"
          ^~~~~~~~~~~~
compilation terminated.
Error: Build failed
```

**Comment by ianharrigan** [comment]
i think the env var should be `WXWIN` not `WINWX` (wrong way round).... also, to be safe, use windows forward slashes... 

![image](https://user-images.githubusercontent.com/3024242/33349924-9778bde6-d49c-11e7-9054-ade0ca28d020.png)

That work?

**Comment by r3d9u11** [comment]
@ianharrigan sure, this is just an typo in my issue.

yep, it works fine:
```
C:\Users\user>echo %WXWIN%
C:\wxWidgets-3.1.0
```
i think that trouble in with path, because it contains both types of path separator (first windows-type, and second unix-type, as I think, Haxe uses it by default): C:\wxWidgets-3.1.0\include/wx/platform.h

**Comment by r3d9u11** [comment]
@ianharrigan ok, I've changed WXWIN from `C:\wxWidgets-3.1.0` to `C:\\wxWidgets-3.1.0` and now path looks more valid, but compilation failed

**Comment by r3d9u11** [comment]
@ianharrigan hmm, directory `wxWidgets-3.1.0/include` don't contain file `setup.h`

**Comment by ianharrigan** [comment]
I think you need to build wx also... there are probably precompiled versions you can get too, but iirc i just compiled the .dlls / libs with a make file - not sure how easy that is with mingw though (i used MSVC)

**Comment by r3d9u11** [comment]
@ianharrigan thank you for help! I'll paste results of compilation with MinGW here (when I will get success)

**Comment by r3d9u11** [comment]
@ianharrigan so, I copied setup.h from `C:\wxWidgets-3.1.0\include\wx\msw` to `C:\wxWidgets-3.1.0\include\wx` and wxWidgets was successfully [compiled with MinGW](https://wiki.wxwidgets.org/Compiling_wxWidgets_with_MinGW) (static and shared versions).

but when I tried to compile hxWidgets I've now another exception:
```
Error: In file included from ./src/hx/widgets/GraphicsContext.cpp:59:0:
include/hx/widgets/GraphicsContext.h:84:16: error: 'wxAntialiasMode' was not declared in this scope
    cpp::Struct<wxAntialiasMode, cpp::EnumHandler> antialiasMode;
    ...
    ...
```
but this enum already defined at `C:\wxWidgets-3.1.0\include\wx\graphics.h`

do you have any ideas?
