### ISSUE TITLE
Feature request : Support for tray application / icon

### ISSUE THREAD

**Issue by datee** [haxeui/hxWidgets#52]
Is it possible to get support for having the application minimize to the tray, with a tray menu? I think there is support for this in WxWidgets via wxTaskBarIcon etc?

**Comment by ianharrigan** [comment]
Sure - ill look into it.... Ill probably also add it as an option properly for haxeui-hxwidgets too (assuming it works)... something like `haxe.ui.hxwidgets.minimizeToTray=true`

**Comment by datee** [comment]
Any update on this? I'm writing a haxeui-hxwidgets based app where this would be so good to have :)

**Comment by ianharrigan** [comment]
Ok, got an initial implementation done, see change above for usage.

**Comment by datee** [comment]
Hey thats awesome! Does it support opening a tray menu also?

**Comment by ianharrigan** [comment]
Nope, its doesnt support much at the moment, but its a start at least,
