### ISSUE TITLE
[Haxe 4.1.0] Override not allowed on static functions

### ISSUE THREAD

**Issue by afaur** [haxeui/hxWidgets#68]
After upgrading to haxe 4.1.0 I am getting the following when using hxWidgets:

  - hxWidgets/1,5,1/src/hx/widgets/PropertyGridEvent.hx:30: lines 30-34 : fromPointer: 'override' is not allowed on 'static' functions
  - hxWidgets/1,5,1/src/hx/widgets/MouseEvent.hx:30: lines 30-34 : fromPointer: 'override' is not allowed on 'static' functions

Relevent code lines:
  - https://github.com/haxeui/hxWidgets/blob/master/src/hx/widgets/Event.hx#L38
  - https://github.com/haxeui/hxWidgets/blob/master/src/hx/widgets/PropertyGridEvent.hx#L30
  - https://github.com/haxeui/hxWidgets/blob/master/src/hx/widgets/MouseEvent.hx#L30

**Comment by ianharrigan** [comment]
oh... great... :/

Thanks for the heads up!

**Comment by ianharrigan** [comment]
Are you comfortable using git + haxelib? Ive pushed a fix for this and before i make a haxelib release id like to make sure it works.

**Comment by afaur** [comment]
Verified this is working now.
