### ISSUE TITLE
Error building Showcase, Debian GNU/Linux

### ISSUE THREAD

**Issue by uvtc** [haxeui/hxWidgets#69]
After a `haxelib install hxWidgets`, with haxelibs installed into ~/haxelib, I tried building the showcase like so:

~~~
cd ~/haxelib
cp -r hxWidgets ~/temp
cd ~/temp/hxWidgets/1,5,1/samples/00-Showcase
haxe build.hxml
~~~

but on that last step I get:

~~~
$ haxe build.hxml 
/home/john/haxelib/hxWidgets/1,5,1/src/hx/widgets/PropertyGridEvent.hx:30: lines 30-34 : fromPointer: 'override' is not allowed on 'static' functions
/home/john/haxelib/hxWidgets/1,5,1/src/hx/widgets/MouseEvent.hx:30: lines 30-34 : fromPointer: 'override' is not allowed on 'static' functions
~~~

This is on Debian Testing using wx 3.1.3 and Haxe 4.1.1. The only haxelibs I have installed are hscript, hxcpp, and hxWidgets.

**Comment by ianharrigan** [comment]
Can you try the git version of hxWidgets? If that works ill create a release

**Comment by uvtc** [comment]
Ok. Did:

    haxelib remove hxWidgets
    haxelib git hxWidgets https://github.com/haxeui/hxWidgets.git

then built the Showcase from fresh source and it worked.

**Comment by ianharrigan** [comment]
OK, cool - ill make a release a little later.

**Comment by simonRiep** [comment]
Hi there,

I got the same problem on windows, after switching too git-version I now get on build:

Error: PlatformInfo.cpp
./src/hx/widgets/PlatformInfo.cpp(110): error C2039: "IsInstanceNotEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(110): error C3861: "IsInstanceNotEq": Name not found.
./src/hx/widgets/PlatformInfo.cpp(111): error C2039: "IsInstanceEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(111): error C3861: "IsInstanceEq": Name not found.
./src/hx/widgets/PlatformInfo.cpp(125): error C2039: "IsInstanceNotEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(125): error C3861: "IsInstanceNotEq": Name not found.
./src/hx/widgets/PlatformInfo.cpp(126): error C2039: "IsInstanceEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(126): error C3861: "IsInstanceEq": Name not found.
./src/hx/widgets/PlatformInfo.cpp(132): error C2039: "IsInstanceEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(132): error C3861: "IsInstanceEq": Name not found.
./src/hx/widgets/PlatformInfo.cpp(145): error C2039: "IsInstanceEq" no member of "hx".
./src/hx/widgets/PlatformInfo.cpp(27): note: see declaration of "hx"
./src/hx/widgets/PlatformInfo.cpp(145): error C3861: "IsInstanceEq": Name not found.

Error: Build failed


Is this a new bug / did I miss something on installation / should i open a new bug-report?

**Comment by ianharrigan** [comment]
hmmm, what versions of:

* haxe
* hxcpp
* hxWidgets
* wxWidgets

are you using i dont think its related to wxWidgets though - my guess is hxcpp)

**Comment by simonRiep** [comment]
Haxe Compiler 4.2.0-rc.1+64c5ec461
hxcpp: 4.0.8 4.0.19 4.0.52 4.0.64 [4.1.1]
hxWidgets: [git]
wxWidgets in C:\wxWidgets-3.1.3 - so 3.1.3 just from todays download

Should I switch hxcpp too git too?

**Comment by ianharrigan** [comment]
I would try git hxcpp (and rebuild hxcpp too ofc - instructions are in the hxcpp repo). It may be a haxe issue to has im on 4.1.1 (not sure though if that is it)

**Comment by simonRiep** [comment]
working with hxcpp from git and rebuilding worked so far - compiling works - after copying the .dlls the main.exe started for the 00-Blank project and showed everything so far so correct!

**Comment by ianharrigan** [comment]
sweet! Good to remember then that hxcpp needs to be git
