### ISSUE TITLE
fatal error C1083 when compiling on Windows 10

### ISSUE THREAD

**Issue by s1-en** [haxeui/hxWidgets#74]
I have Visual Studio 2019 installed but when trying to build the sample created with `haxelib run haxeui-core create hxwidgets" I get the error:

fatal error C1083: Cannot open include file: 'typeinfo.h': No such file or directory

I also have wxWidgets on `C:\wxWidgets-3.1.4` and mapped to `WXWIN` environment variable and built using nmake with the instructions found here http://haxeui.org/getting-started/haxeui-hxwidgets/

What could I be missing?

**Comment by ianharrigan** [comment]
Hi, sorry, been only holiday - is this still an issue? Can you run any of the normal wxWidgets applications (no haxe, no hxWidgets)?

**Comment by s1-en** [comment]
Apologies but I'm not familiar with how wxWidgets works in general, I was just following the instructions since Haxe is something I do have some inkling of knowing by proxy of ActionScript 3

**Comment by ianharrigan** [comment]
Hmmm, when you compile the hxWidgets / haxeui app, do you get a "using wxWidgets from C:\wxWidgets-3.1.4" printed out? What versions of haxe, hxWidgets, haxeui-core and haxeui-hxwidgets are you using?

Cheers,
Ian

**Comment by ianharrigan** [comment]
Also, can you zip up your project so i can test this end?

**Comment by s1-en** [comment]
For the versions, I have:

- haxe - 4.2.1
- hxWidgets - 1.7.2
- haxeui-core - 1.2.3
- haxeu-hxwidgets - 1.2.3

When I compile the project with `haxe hxwidgets.hxml`, I do get this:

```
Using wxWidgets from: C:\wxWidgets-3.1.4\lib\vc_lib
 - Parsing include: C:/Users/s1-en/scoop/apps/haxe/current/lib/hxcpp/4,0,52/toolchain/msvc-toolchain.xml
 - Parsing compiler: C:/Users/s1-en/scoop/apps/haxe/current/lib/hxcpp/4,0,52/toolchain/common-defines.xml
 - Parsing include: C:\Users\s1-en\.hxcpp_config.xml (section "exes")
```

And here's the zip of the project source

[hui-test.zip](https://github.com/haxeui/hxWidgets/files/6258117/hui-test.zip)

**Comment by ianharrigan** [comment]
Is that the full output? Do you have any "strange" configuration changes you have made to hxcpp or is it all just default hxcpp stuff? I tried your project this end and it all worked just fine - so there has to be something strange with your install of _something_ 

![image](https://user-images.githubusercontent.com/3024242/113594080-78dc4000-9637-11eb-83a1-798256b283cd.png)

**Comment by s1-en** [comment]
Thank you so much, your reply prompted me to investigate hxcpp real close. I never made any changes to hxcpp but apparently the issue was that for some reason it had the older version 4.0.52 set as the "main" version instead of the newer 4.2.1. I uninstalled hxcpp and reinstalled and now it's compiling properly!

**Comment by ianharrigan** [comment]
Perfect! I wont try and understand what the issue with hxcpp was, its a complex beast, but glad its working! If you are happy this is resolved can you close this when you get moment? Cheers!
