### ISSUE TITLE
cant find how to fix it

### ISSUE THREAD

**Issue by yairarad10** [haxeui/hxWidgets#80]
source/Caching.hx:174: cached thorns
source/Caching.hx:174: cached tutorial
source/Caching.hx:174: cached winter-horrorland
source/Caching.hx:179: Finished caching...
source/Caching.hx:183: false
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from TitleState::create TitleState.hx line 57
Called from polymod.Polymod::init polymod/Polymod.hx line 224
Called from polymod.backends.PolymodAssets::init polymod/backends/PolymodAssets.hx line 127
Called from polymod.backends.LimeBackend::init polymod/backends/LimeBackend.hx line 131

**Comment by ianharrigan** [comment]
OK, ill close this then :)
