### ISSUE TITLE
MacOS Building problems

### ISSUE THREAD

**Issue by BushTrain460615** [haxeui/hxWidgets#85]
Error: ./src/hx/widgets/TaskBarIcon.cpp:86:36: error: no viable conversion from 'wxIcon' to incomplete type 'const wxBitmapBundle'
HXDLIN(  27)            (*(_hx_tmp)).SetIcon(_hx_tmp1,_hx_tmp2);
                                             ^~~~~~~~
/opt/homebrew/include/wx-3.2/wx/taskbar.h:21:7: note: forward declaration of 'wxBitmapBundle'
class wxBitmapBundle;
      ^
/opt/homebrew/include/wx-3.2/wx/osx/taskbarosx.h:33:40: note: passing argument to parameter 'icon' here
    bool SetIcon(const wxBitmapBundle& icon, const wxString& tooltip = wxEmptyString);
                                       ^
./src/hx/widgets/TaskBarIcon.cpp:108:36: error: no viable conversion from 'wxIcon' to incomplete type 'const wxBitmapBundle'
HXDLIN(  48)            (*(_hx_tmp)).SetIcon(_hx_tmp1,_hx_tmp2);
                                             ^~~~~~~~
/opt/homebrew/include/wx-3.2/wx/taskbar.h:21:7: note: forward declaration of 'wxBitmapBundle'
class wxBitmapBundle;
      ^
/opt/homebrew/include/wx-3.2/wx/osx/taskbarosx.h:33:40: note: passing argument to parameter 'icon' here
    bool SetIcon(const wxBitmapBundle& icon, const wxString& tooltip = wxEmptyString);

When I try to build a crash reporter it just gives me this error

**Comment by BushTrain460615** [comment]
Update
 It's when I build anything
also I reinstalled the brew thing and it still won't work

**Comment by ianharrigan** [comment]
Are you using hxWidgets git version? What version of wxWidgets? There seems to be some inconsistencies between wx versions.

**Comment by BushTrain460615** [comment]
im using the stable version of HxWigets

**Comment by ianharrigan** [comment]
Can you try the git version of hxwidgets?

**Comment by BushTrain460615** [comment]
sure

**Comment by BushTrain460615** [comment]
Error: ./src/hx/widgets/TaskBarIcon.cpp:86:36: error: no viable conversion from 'wxIcon' to incomplete type 'const wxBitmapBundle'
HXDLIN(  27)            (*(_hx_tmp)).SetIcon(_hx_tmp1,_hx_tmp2);
                                             ^~~~~~~~
/opt/homebrew/include/wx-3.2/wx/taskbar.h:21:7: note: forward declaration of 'wxBitmapBundle'
class wxBitmapBundle;
      ^
/opt/homebrew/include/wx-3.2/wx/osx/taskbarosx.h:33:40: note: passing argument to parameter 'icon' here
    bool SetIcon(const wxBitmapBundle& icon, const wxString& tooltip = wxEmptyString);
                                       ^
./src/hx/widgets/TaskBarIcon.cpp:108:36: error: no viable conversion from 'wxIcon' to incomplete type 'const wxBitmapBundle'
HXDLIN(  48)            (*(_hx_tmp)).SetIcon(_hx_tmp1,_hx_tmp2);
                                             ^~~~~~~~
/opt/homebrew/include/wx-3.2/wx/taskbar.h:21:7: note: forward declaration of 'wxBitmapBundle'
class wxBitmapBundle;
      ^
/opt/homebrew/include/wx-3.2/wx/osx/taskbarosx.h:33:40: note: passing argument to parameter 'icon' here
    bool SetIcon(const wxBitmapBundle& icon, const wxString& tooltip = wxEmptyString);
                                       ^
2 errors generated.
Error: Build failed

I think I got the same error

**Comment by BushTrain460615** [comment]
<img width="1482" alt="Screenshot 2022-09-03 at 10 33 21 AM" src="https://user-images.githubusercontent.com/72326501/188277682-cc5f6424-6764-47c4-9dca-62d265bdb445.png">

**Comment by BushTrain460615** [comment]
<img width="226" alt="Screenshot 2022-09-03 at 10 50 39 AM" src="https://user-images.githubusercontent.com/72326501/188278320-8d073db2-ba57-4f5f-b643-395c294741dd.png">

**Comment by BushTrain460615** [comment]
<img width="964" alt="Screenshot 2022-09-03 at 10 58 23 AM" src="https://user-images.githubusercontent.com/72326501/188278600-e73593c7-c2b9-4973-9cea-16773e57ba20.png">
here are the errors I get if I remove haxeui-hxwidgets

**Comment by ianharrigan** [comment]
hmmm, what about using git everything? Including wxWidgets, so:

* git haxeui-core
* git haxeui-hxwidgets
* git hxWidgets
* git wxWidgets (you can find out how to build it here: https://github.com/haxeui/hxWidgets#building-wxwidgets-from-source-linux--osx)

**Comment by BushTrain460615** [comment]
ok I can try that

**Comment by BushTrain460615** [comment]
I got 1 error

**Comment by BushTrain460615** [comment]
../src/common/imagtiff.cpp:37:14: fatal error: 'tiff.h' file not found
    #include "tiff.h"
             ^~~~~~~~
1 error generated.
make: *** [corelib_imagtiff.o] Error 1

**Comment by BushTrain460615** [comment]
https://github.com/BushTrain460615/stupid-crash-reporter-errors/blob/main/errors.txt

Here is a whole list of errors I get after doing that

**Comment by ianharrigan** [comment]
You sure you built wx correctly from git? And verified the version with `wx-config --version`

Can you build / run the wx samples? (not haxe, not haxeui, c++)

**Comment by BushTrain460615** [comment]
> ../src/common/imagtiff.cpp:37:14: fatal error: 'tiff.h' file not found
> #include "tiff.h"
> ^~~~~~~~
> 1 error generated.
> make: *** [corelib_imagtiff.o] Error 1

This is what happens when I try to build wxWidgets

**Comment by BushTrain460615** [comment]
I fixed it

**Comment by BushTrain460615** [comment]
so what do I have to build and also how do I set it as the main wxWidgets

**Comment by BushTrain460615** [comment]
<img width="1680" alt="Screenshot 2022-09-03 at 6 20 48 PM" src="https://user-images.githubusercontent.com/72326501/188290404-67d456a7-124d-468f-95d1-20b99fd969e0.png">
when building with c++ it works

**Comment by ianharrigan** [comment]
Great... was the issue about the sub modules? Ie, when you cloned it via git you didnt init / clone the sub modules?

Anyways, now thats working you should be able to open a new command window and type `./wx-config --version` and see the new version.

After that, try and build a hxWidgets / haxeui-hxwidgets application and see what happens, you want to try:

* git haxeui-core
* git haxeui-hxwidgets
* git hxWidgets

**Comment by BushTrain460615** [comment]
<img width="475" alt="Screenshot 2022-09-04 at 8 54 05 AM" src="https://user-images.githubusercontent.com/72326501/188317173-acb805be-3d11-4854-ae8a-88dc067bc5f8.png">
I don't think this is supposed to happen

**Comment by BushTrain460615** [comment]
https://user-images.githubusercontent.com/72326501/188336019-bb935420-4c16-41f7-a828-890ac4307187.mov

here is what happens when I try to build one of the samples

**Comment by BushTrain460615** [comment]
so Is there nothing you can do to help

**Comment by ianharrigan** [comment]
OK, so just to understand, you are using git "everything", right? wx c++ samples compile and run fine, but haxeui-hxwidgets samples dont... that accurate?

Ill try later on my mac and see what i get.

Cheers,
Ian

**Comment by BushTrain460615** [comment]
ok

**Comment by ianharrigan** [comment]
OK, so i just tested on my mac and i had no issues what so ever:
* cloned wxWidgets repo (https://github.com/wxWidgets/wxWidgets), making sure to initialize the submodules
* created a wx_build dir in the and navigated to it via command line
* ran `../configure --with-opengl --disable-shared`
* wait for that to work (and be successful)
* ran `make -j3` (wait for ages :) )
* once done `sudo make install`
* opened another terminal tab and did `./wx-config --version` to make sure every was ok (reported 3.3.0)
* created another dir somewhere `haxeui-test-app
* opened a terminal in that dir and ran `haxelib run haxeui-core create hxwidgets` to create a skeleton app
* ran `haxe hxwidgets.hxml` (wait another age)
* once done `./build/hxwidgets/Main`
![Screenshot 2022-09-10 at 12 24 00](https://user-images.githubusercontent.com/3024242/189479362-71950aaa-c3d1-430c-a286-d2da3b996692.png)
Note im using git _everything_, that is:
* git haxeui-core
* git haxeui-hxwidgets
* git hxWidgets
* git wxWidgets

You might want to double check you are using git everything, a good idea would be to get rid of the haxelibs (you can just delete the folders in haxelib) and start again, another alternative is to use `haxelib dev haxeui-core /path/to/haxeui-core` and then manage that folder external to haxelib (sometimes haxelib git seems to do weird things).

Cheers,
Ian

**Comment by BushTrain460615** [comment]
i will try this when i get back to my laptop

**Comment by BushTrain460615** [comment]
<img width="480" alt="Screenshot 2022-09-14 at 6 49 07 PM" src="https://user-images.githubusercontent.com/72326501/190282101-31663a91-f881-4da6-ae7b-d4043c3d7383.png">

**Comment by ianharrigan** [comment]
im not sure what that error means what is "//this"... where is that?

**Comment by BushTrain460615** [comment]
I figured it out

**Comment by ianharrigan** [comment]
What was the problem?

**Comment by BushTrain460615** [comment]
> *ran make -j3 (wait for ages :) )
<img width="561" alt="Screenshot 2022-09-21 at 12 36 49 PM" src="https://user-images.githubusercontent.com/72326501/191573101-74edb388-65c8-44c0-b1cd-84af7131b3ac.png">

**Comment by BushTrain460615** [comment]
also I know yours builds without error so I wanted to know if you can see if it is the thing I am build that is the problem 
https://github.com/gedehari/IzzyEngine/tree/master/crash-dialog
