### ISSUE TITLE
00-Showcase: Assertion failure: only normal menu items can have bitmaps

### ISSUE THREAD

**Issue by TiZ-EX1** [haxeui/hxWidgets#9]
The sample application has an assertion failure. It works if I click continue, but I figured I should report it anyways.

ASSERT INFO:
../src/gtk/menu.cpp(724): assert "Assert failure" failed in SetBitmap(): only normal menu items can have bitmaps

BACKTRACE:
[1] wxMenuItem::SetBitmap(wxBitmap const&)
[2] hx::widgets::MenuItem_obj::setBitmap(hx::ObjectPtrhx::widgets::Bitmap_obj)
[3] Main_obj::main()
[4] main
[5] __libc_start_main
[6] _start

**Comment by ianharrigan** [comment]
Ah ha, i added the menus and only tested windows... So the underlying wxWidgets impl obviously doesnt like bitmaps in menus, which is fine - but i wonder how we can know that at runtime...

**Comment by TiZ-EX1** [comment]
The funny thing here is that GTK definitely can use images in menus. I wonder if wxWidgets on GTK simply doesn't bother letting you. The only wxWidgets app I have on my system is Audacity, and it doesn't use any menu icons at all.

**Comment by ianharrigan** [comment]
Maybe very be a wxWidgets limitation, but either way we should be able to detect that somehow and simply to try, and thus not get an assertion - or some type of silent assertion technique

**Comment by ibilon** [comment]
I don't remember having this issue,
what version of wxWidgets and gtk+ do you have?

**Comment by TiZ-EX1** [comment]
From Ubuntu 15.10's repos, version 3.0.2 of libwxgtk and version 3.16.7 of GTK+.

**Comment by ianharrigan** [comment]
I saw a similar annoyance with the progressbar (gauge) in the showcase. Its value is linked to to a slider and if you go over the progress max value you get an assertion... Not good / clean. Easy to fix in that case of course (just check bounds in the wrapper before using the extern function), but it doesnt happen in windows or mac and makes me wonder if we can come up with some type of general assertion strategy to "veto" this type of critical assertion. 

Its also very likely (almost certain) that its assertions would be stripped from release builds of wxWidgets

**Comment by ianharrigan** [comment]
Can we retry this with latest and see if this issue can be closed? Thanks.
